fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana','orangess','orange']
new_fr=fruits.copy()
print(new_fr)
print(new_fr.clear())
# fruits.reverse()
# print(fruits)
# fruits.sort()
# print(fruits)
# print(fruits.index("orange"))
# print(fruits.count("orange"))
# print(fruits.index("orangess"))
# fruits.pop()
# print(fruits)
# fruits.pop(9)
# print(fruits)
# fruits.pop(1)
# print(fruits)
# fruits.remove("kiwi")
# print(fruits)
# fruits.remove("bananas")
# print(fruits)
# fruits.insert(1,"papaya")
# print(fruits)
# fruits.insert(len(fruits),"papaya")
# print(fruits)
# fruits.append("brinjal")
# print(fruits)