demo_s1={"Delhi","Goa","Bangalore","Hyd","Kerala"}
demo_s2={"Delhi","Goa","Bangalore","Punjab","Kashmir","Vizag","Pune"}
y=demo_s1.issuperset(demo_s2)
print(y)
x=demo_s1.issubset(demo_s2)
print(x)
# demo_s2.difference_update(demo_s1)
# print(demo_s2)
# demo_s8= demo_s2.difference(demo_s1)
# print(demo_s8)
# demo_s7= demo_s1.difference(demo_s2)
# print(demo_s7)
# demo_s1.symmetric_difference_update(demo_s2)
# print(demo_s1)
# demo_s6=demo_s1.symmetric_difference(demo_s2)
# print(demo_s6)
# demo_s1.intersection_update(demo_s2)
# print(demo_s1)
# demo_s5=demo_s1.intersection(demo_s2)
# print(demo_s5)
# demo_s3=demo_s1.union(demo_s2)
# print(demo_s3)
# demo_s1.update(demo_s2)
# print(demo_s1)

# print(demo_s2)
# print(demo_s3)

# demo_s1.clear()
# print(demo_s1)
# demo_s1.pop()
# print(demo_s1)
# demo_s1.add("Vizag")
# print(demo_s1)
# demo_s1.remove("Vizag")
# print(demo_s1)
# demo_s1.discard("Vizagss")
# print(demo_s1)