demo_t1 = (1, 2, 3, 4, 5, 6)
demo_t2 = ("Delhi", "Goa", "Bangalore", "Punjab", "Kashmir", "Vizag", "Pune", "Goa")
demo_t3 = (True, False, True, True)
demo_t4 = (1, 56.789, "Python", True)
# print(demo_t2[5])
# print(len(demo_t1))
# print(type(demo_t4))
# print(demo_t2.count("Goa"))
# print(demo_t2.index("Goa"))
# print(demo_t2.index("Goa", 2, len(demo_t2)))
# print(demo_t2[3])
print(demo_t2[1:len(demo_t2)])
print(demo_t2[1:len(demo_t1)])
join_t = demo_t1 + demo_t4
print(join_t)
print(type(join_t))
for x in demo_t2:
    print(x)
